#!/usr/bin/env python3
"""
Lu Example Plugin - MCP Server Implementation

This plugin demonstrates the Lu plugin architecture with two example tools:
- example_greet: Simple greeting (no vault output)
- example_summarize: Generate vault-ready markdown (vault output)

Run with:
    uv run mcp dev src/server.py
"""

import os
from datetime import datetime

from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import TextContent, Tool


# Create the MCP server
server = Server("lu-example")


@server.list_tools()
async def list_tools() -> list[Tool]:
    """Return the list of tools this plugin provides."""
    return [
        Tool(
            name="example_greet",
            description="Generate a friendly greeting message",
            inputSchema={
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The name to greet",
                    },
                    "style": {
                        "type": "string",
                        "description": "Greeting style: formal, casual, or pirate",
                        "enum": ["formal", "casual", "pirate"],
                        "default": "casual",
                    },
                },
                "required": ["name"],
            },
        ),
        Tool(
            name="example_summarize",
            description="Summarize text and format as vault-ready markdown",
            inputSchema={
                "type": "object",
                "properties": {
                    "text": {
                        "type": "string",
                        "description": "The text to summarize",
                    },
                    "title": {
                        "type": "string",
                        "description": "Title for the summary note",
                    },
                },
                "required": ["text"],
            },
        ),
    ]


@server.call_tool()
async def call_tool(name: str, arguments: dict) -> list[TextContent]:
    """Handle tool calls."""
    if name == "example_greet":
        return await _handle_greet(arguments)
    elif name == "example_summarize":
        return await _handle_summarize(arguments)
    else:
        raise ValueError(f"Unknown tool: {name}")


async def _handle_greet(arguments: dict) -> list[TextContent]:
    """Generate a greeting message."""
    name = arguments.get("name")
    if not name:
        raise ValueError("name is required")

    style = arguments.get("style", "casual")

    greetings = {
        "formal": f"Good day, {name}. It is a pleasure to make your acquaintance.",
        "casual": f"Hey {name}! Great to see you!",
        "pirate": f"Ahoy, {name}! Welcome aboard, ye scallywag!",
    }

    greeting = greetings.get(style, greetings["casual"])

    return [TextContent(type="text", text=greeting)]


async def _handle_summarize(arguments: dict) -> list[TextContent]:
    """
    Summarize text and return vault-ready markdown.

    When vault_output=true in the manifest, Lu will save this output
    to the specified output_path in the user's vault.
    """
    text = arguments.get("text")
    if not text:
        raise ValueError("text is required")

    title = arguments.get("title", "Summary")
    now = datetime.now()

    # For a real plugin, you might use an LLM to generate the summary.
    # This example just extracts key information.
    word_count = len(text.split())
    char_count = len(text)
    first_sentence = text.split(".")[0] + "." if "." in text else text[:100]

    # Format as vault-ready markdown with frontmatter
    content = f"""---
date: {now.strftime("%Y-%m-%d")}
created: {now.isoformat()}
source: lu-example
type: summary
---

# {title}

## Overview

{first_sentence}

## Statistics

- **Word count:** {word_count}
- **Character count:** {char_count}
- **Generated:** {now.strftime("%Y-%m-%d %H:%M")}

## Original Text

> {text[:500]}{"..." if len(text) > 500 else ""}

---
*Generated by lu-example plugin*
"""

    return [TextContent(type="text", text=content)]


async def main():
    """Run the MCP server."""
    # Check for required credentials (example)
    api_key = os.environ.get("EXAMPLE_API_KEY")
    if not api_key:
        # Log warning but continue - some tools might not need credentials
        import sys
        print("Warning: EXAMPLE_API_KEY not set", file=sys.stderr)

    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            server.create_initialization_options(),
        )


if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
